### ISSUE TITLE
Tag mis-match

### ISSUE THREAD

**Issue by fabaff** [MatsNl/pyatag#7]
The latest release seems to be 0.3.5.1. The latest tag 3.5.1 which creates the GitHub release.

Could you please fix the tag?

This is an  issue for the distribution packages which are using the GitHub source.

**Comment by MatsNl** [comment]
Can you confirm this works as expected now?

**Comment by AMDmi3** [comment]
Please consider removing the tag (and recreating as 0.3.5.1 if you like). Automated tools which track latest github releases may be bugged by it and treat it as the latest version forever.

**Comment by fabaff** [comment]
Can you please delete the tag for 3.5.1?
